#!/usr/bin/env zsh

function _load_function() {
  for file in "${ZDOTDIR:-$HOME/.config/zsh}/functions/"*.zsh; do
    [ -r "$file" ] && source "$file" || echo -e "==>  Failed to source $file"
  done
}

function _load_completion() {
  for file in "${ZDOTDIR:-$HOME/.config/zsh}/completions/"*.zsh; do
    [ -r "$file" ] && source "$file" || echo -e "==>  Failed to source $file"
  done
}

function _load_prompt() {
  source $ZDOTDIR/prompt.zsh || echo -e "==>  Failed to source prompt settings."
}

function _load_plugin() {
  source $ZDOTDIR/plugin.zsh || echo -e "==>  Failed to source plugin settings."
}

# main stuff
[[ -r $ZDOTDIR/startup.zsh ]] && source $ZDOTDIR/startup.zsh
_load_plugin
_load_prompt
_load_function
_load_completion
[[ -r $ZDOTDIR/custom.zsh ]] && source $ZDOTDIR/custom.zsh
