#!/usr/bin/env zsh

env_dir="$ZDOTDIR/src/env.zsh"
terminal_dir="$ZDOTDIR/src/terminal.zsh"

if ! . "$env_dir" 2>/dev/null; then
  echo "Error: Could not source ${env_dir}"
fi

if ! . "$terminal_dir" 2>/dev/null; then
  echo "Error: Could not source ${terminal_dir}"
fi
